In [1]:
import pandas as pd
import json

In [16]:
file = "Resources/species.csv"

In [17]:
species = pd.read_csv(file)
species.head()

/Users/albertogonzalez/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Species ID,Park Name,Category,Order,Family,Scientific Name,Common Names,Record Status,Occurrence,Nativeness,Abundance,Seasonality,Conservation Status,Unnamed: 13
0,ACAD-1000,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Approved,Present,Native,Rare,Resident,NaN,NaN
1,ACAD-1001,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Approved,Present,Native,Abundant,NaN,NaN,NaN
2,ACAD-1002,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Approved,Present,Not Native,Common,NaN,Species of Concern,NaN
3,ACAD-1003,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Approved,Not Confirmed,Native,NaN,NaN,Endangered,NaN
4,ACAD-1004,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Approved,Present,Unknown,Common,Breeder,NaN,NaN

In [18]:
species.drop(species.iloc[:, 9:], inplace=True, axis=1)

In [19]:
species.drop(columns = ["Species ID"], inplace=True, axis=1)

In [20]:
species.drop(columns = ["Record Status"], inplace=True, axis=1)

In [21]:
species.head()

,Park Name,Category,Order,Family,Scientific Name,Common Names,Occurrence
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Present
1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Present
2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Present
3,Acadia National Park,Mammal,Carnivora,Canidae,Canis lupus,"Eastern Timber Wolf, Gray Wolf, Timber Wolf",Not Confirmed
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Present

In [22]:
species_1 = species["Occurrence"]=="Present"

In [23]:
present_species = species[species_1]

In [24]:
present_species

,Park Name,Category,Order,Family,Scientific Name,Common Names,Occurrence
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Present
1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Present
2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Present
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Present
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Present
...,...,...,...,...,...,...,...
119243,Zion National Park,Vascular Plant,Solanales,Solanaceae,Solanum triflorum,Cut-Leaf Nightshade,Present
119244,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis arizonica,Canyon Grape,Present
119245,Zion National Park,Vascular Plant,Vitales,Vitaceae,Vitis vinifera,Wine Grape,Present
119246,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Larrea tridentata,Creosote Bush,Present
119247,Zion National Park,Vascular Plant,Zygophyllales,Zygophyllaceae,Tribulus terrestris,Puncture Vine,Present

In [25]:
animals = present_species["Category"].unique().tolist()
animals_1 = animals[0:4]
animals_1

['Mammal', 'Bird', 'Reptile', 'Amphibian']

In [26]:
animal_species = present_species[present_species["Category"].isin(animals_1)]
animal_species.head()

,Park Name,Category,Order,Family,Scientific Name,Common Names,Occurrence
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose,Present
1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi...",Present
2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote",Present
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re...",Present
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter",Present

In [27]:
animal_species.drop(columns = ["Occurrence"], inplace=True, axis=1)

/Users/albertogonzalez/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [28]:
animal_species

,Park Name,Category,Order,Family,Scientific Name,Common Names
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose
1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi..."
2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote"
4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re..."
8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter"
...,...,...,...,...,...,...
117865,Zion National Park,Amphibian,Anura,Bufonidae,Bufo woodhousii,Woodhouse's Toad
117866,Zion National Park,Amphibian,Anura,Hylidae,Hyla arenicolor,Canyon Treefrog
117867,Zion National Park,Amphibian,Anura,Ranidae,Rana pipiens,Northern Leopard Frog
117868,Zion National Park,Amphibian,Anura,Scaphiopodidae,Spea intermontana,Great Basin Spadefoot
117869,Zion National Park,Amphibian,Caudata,Ambystomatidae,Ambystoma tigrinum,Tiger Salamander

In [29]:
animal_species['Park Name'] = animal_species['Park Name'].replace(['Black Canyon of the Gunnison National Park','Denali National Park and Preserve'
                                                                   ,'Gates Of The Arctic National Park and Preserve','Glacier Bay National Park and Preserve',
                                                                  'Great Sand Dunes National Park and Preserve','Haleakala National Park',
                                                                  'Hawaii Volcanoes National Park','Katmai National Park and Preserve','Lake Clark National Park and Preserve','Redwood National Park',
                                                                  'Sequoia and Kings Canyon National Parks'],['Black Canyon Of The Gunnison National Park','Denali National Park & Preserve',
                                                                  'Gates Of The Arctic National Park & Preserve','Glacier Bay National Park & Preserve',
                                                                  'Great Sand Dunes National Park & Preserve','HaleakalƒÅ National Park',
                                                                  "Hawai'i Volcanoes National Park",'Katmai National Park & Preserve',
                                                                  'Lake Clark National Park & Preserve','Redwood National and State Parks','Sequoia & Kings Canyon National Parks'])

<ipython-input-29-99a39bff1f84>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  animal_species['Park Name'] = animal_species['Park Name'].replace(['Black Canyon of the Gunnison National Park','Denali National Park and Preserve'

In [30]:
species_json = (animal_species.groupby(["Park Name"], as_index=True)
                .apply(lambda x: x[["Category", "Order", "Family", "Scientific Name", "Common Names"]].to_dict("r")).reset_index()
                .rename(columns={0: "Animals"})
                .to_json("Resources/park_species.json", orient="records"))

/Users/albertogonzalez/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:1549: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  warnings.warn(

In [31]:
animal_species.to_csv("Resources/park_species.csv")

In [25]:
x = "Resources/park_species.csv"
x_df = pd.read_csv(x)
x_df

,Unnamed: 0,Park Name,Category,Order,Family,Scientific Name,Common Names
0,0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose
1,1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi..."
2,2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote"
3,4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re..."
4,8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter"
...,...,...,...,...,...,...,...
16201,117865,Zion National Park,Amphibian,Anura,Bufonidae,Bufo woodhousii,Woodhouse's Toad
16202,117866,Zion National Park,Amphibian,Anura,Hylidae,Hyla arenicolor,Canyon Treefrog
16203,117867,Zion National Park,Amphibian,Anura,Ranidae,Rana pipiens,Northern Leopard Frog
16204,117868,Zion National Park,Amphibian,Anura,Scaphiopodidae,Spea intermontana,Great Basin Spadefoot
16205,117869,Zion National Park,Amphibian,Caudata,Ambystomatidae,Ambystoma tigrinum,Tiger Salamander

In [30]:
# Removing Park with incomplete info
x_df_1 = x_df["Park Name"]!="Wrangell - St Elias National Park and Preserve"

In [31]:
x_df_1

0        True
1        True
2        True
3        True
4        True
         ...
16201    True
16202    True
16203    True
16204    True
16205    True
Name: Park Name, Length: 16206, dtype: bool

In [32]:
x_df_new = x_df[x_df_1]

In [33]:
x_df_new

,Unnamed: 0,Park Name,Category,Order,Family,Scientific Name,Common Names
0,0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose
1,1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi..."
2,2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote"
3,4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re..."
4,8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter"
...,...,...,...,...,...,...,...
16201,117865,Zion National Park,Amphibian,Anura,Bufonidae,Bufo woodhousii,Woodhouse's Toad
16202,117866,Zion National Park,Amphibian,Anura,Hylidae,Hyla arenicolor,Canyon Treefrog
16203,117867,Zion National Park,Amphibian,Anura,Ranidae,Rana pipiens,Northern Leopard Frog
16204,117868,Zion National Park,Amphibian,Anura,Scaphiopodidae,Spea intermontana,Great Basin Spadefoot
16205,117869,Zion National Park,Amphibian,Caudata,Ambystomatidae,Ambystoma tigrinum,Tiger Salamander

In [34]:
x_df_new.reset_index(inplace=True)

In [35]:
x_df_new

,index,Unnamed: 0,Park Name,Category,Order,Family,Scientific Name,Common Names
0,0,0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose
1,1,1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi..."
2,2,2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote"
3,3,4,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re..."
4,4,8,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter"
...,...,...,...,...,...,...,...,...
15964,16201,117865,Zion National Park,Amphibian,Anura,Bufonidae,Bufo woodhousii,Woodhouse's Toad
15965,16202,117866,Zion National Park,Amphibian,Anura,Hylidae,Hyla arenicolor,Canyon Treefrog
15966,16203,117867,Zion National Park,Amphibian,Anura,Ranidae,Rana pipiens,Northern Leopard Frog
15967,16204,117868,Zion National Park,Amphibian,Anura,Scaphiopodidae,Spea intermontana,Great Basin Spadefoot
15968,16205,117869,Zion National Park,Amphibian,Caudata,Ambystomatidae,Ambystoma tigrinum,Tiger Salamander

In [36]:
x_df_new.drop(columns=["index", "Unnamed: 0"], axis=1, inplace=True)

/Users/abayomi/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [37]:
x_df_new

,Park Name,Category,Order,Family,Scientific Name,Common Names
0,Acadia National Park,Mammal,Artiodactyla,Cervidae,Alces alces,Moose
1,Acadia National Park,Mammal,Artiodactyla,Cervidae,Odocoileus virginianus,"Northern White-Tailed Deer, Virginia Deer, Whi..."
2,Acadia National Park,Mammal,Carnivora,Canidae,Canis latrans,"Coyote, Eastern Coyote"
3,Acadia National Park,Mammal,Carnivora,Canidae,Vulpes vulpes,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re..."
4,Acadia National Park,Mammal,Carnivora,Mustelidae,Lutra canadensis,"Otter, River Otter"
...,...,...,...,...,...,...
15964,Zion National Park,Amphibian,Anura,Bufonidae,Bufo woodhousii,Woodhouse's Toad
15965,Zion National Park,Amphibian,Anura,Hylidae,Hyla arenicolor,Canyon Treefrog
15966,Zion National Park,Amphibian,Anura,Ranidae,Rana pipiens,Northern Leopard Frog
15967,Zion National Park,Amphibian,Anura,Scaphiopodidae,Spea intermontana,Great Basin Spadefoot
15968,Zion National Park,Amphibian,Caudata,Ambystomatidae,Ambystoma tigrinum,Tiger Salamander

In [38]:
x_df_new.to_csv("Resources/park_species.csv")

In [39]:
species_json = (x_df_new.groupby(["Park Name"], as_index=True)
                .apply(lambda x: x[["Category", "Order", "Family", "Scientific Name", "Common Names"]].to_dict("r")).reset_index()
                .rename(columns={0: "Animals"})
                .to_json("Resources/park_species.json", orient="records"))